config/routes.rb
Rails.application.routes.draw do
  get 'oauths/connect'
  get 'oauths/callback'
  
  root 'pages#home'

  get 'instagram/user_recent_media'
  get 'instagram/search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
  before_action :set_client, only: [:user_recent_media, :search]
  
  def user_recent_media
    @user = @client.user
    @user_recent_media = @client.user_recent_media
  end
  
  def search
    if !@client.tag_search(params[:q]).empty? && !params[:q].nil?
      @tags = @client.tag_search(params[:q])
      @tag_recent_media = @client.tag_recent_media(@tags[0].name)
    end
  end
  
  private
  
  def set_client
    if session[:access_token]
      @client = Instagram.client(access_token: session[:access_token])
    else
      redirect_to oauths_connect_path
    end
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL)
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    session[:access_token] = response.access_token
    redirect_to instagram_user_recent_media_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instagram/search.html.erb
<div class="row">
  <div class="col s12 m6">
    <br><br>
    <div class="search_wrapper">
      <%= form_tag("/instagram/search", method: "get") do %>
        <%= text_field_tag :q, nil, placeholder: "Entrez un Hashtag avec instavente" %>
        <%= submit_tag "Recherche", class: "btn btn-large orange" %>
      <% end %>
    </div>
    <br><br>
  </div>
  <h5 class="header col s12 light"><%= "#" + @tags[0].name if @tags %></h5>
</div>

<div class="row">
  <% if @tag_recent_media %>
  <% @tag_recent_media.each do |media| %>
  <%= render 'components/card', media: media %>
  <% end %>
  <% end %>
</div>

app/views/instagram/user_recent_media.html.erb
<div class="row">
  <br>
  <h5 class="header col s12 light">Bienvenue,
    <%= @user.username %></h5>
</div>

<div class="row">
  <% @user_recent_media.each do |media| %>
  <%= render 'components/card', media: media %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer orange">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job.</p>


      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Made by <a class="orange-text text-lighten-3" href="http://renyuanz.github.io">Miage Groupe 9</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="orange">
  <div class="nav-wrapper container">
    <%= link_to "InstaVente", root_path, class: "brand-logo" %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Explorez", instagram_user_recent_media_path %></li>
      <li><%= link_to "Search", instagram_search_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instavente</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="section no-pad-bot" id="index-banner">
  <br><br>
  <h1 class="header center orange-text">InstaVente</h1>
  <div class="row center">
    <h5 class="header col s12 light">Découvrez les Ventes du Jour et prenez-les!</h5>
  </div>
  <div class="row center">
    <%= link_to "Connexion via Instagram", oauths_connect_path, class: "btn-large waves-effect waves-light orange" %>
  </div>
  <br><br>

</div>

<div class="section">

  <!--   Icon Section   -->
  <div class="row">
    <div class="col s12 m4">
      <div class="icon-block">
        <h2 class="center light-blue-text"><%= icon 'bolt' %></h2>
        <h5 class="center">Speeds up</h5>

        <p class="light">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>

    <div class="col s12 m4">
      <div class="icon-block">
        <h2 class="center light-blue-text"><%= icon 'users' %></h2>
        <h5 class="center">User Experience</h5>

        <p class="light">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>

    <div class="col s12 m4">
      <div class="icon-block">
        <h2 class="center light-blue-text"><%= icon 'cogs' %></h2>
        <h5 class="center">Easy</h5>

        <p class="light">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
  </div>

</div>